# api-spec.yaml
openapi: 3.0.0
servers:
  - description: Localhost
    url: http://127.0.0.1:4993
info:
  description: This is a series of example API endpoints that may be useful in making AusTraits more accessible to a wider audience
  version: "1.0.0"
  title: AusTraits API

paths:
  /health-check:
    get:
      summary: "ALL users: Determine if the API is running and listening as expected"
      responses:
       default:
        description: Default response.
      parameters:
  /trait-count:
    get:
      summary: "For ALA: Returns the number of traits per taxa for any given species"
      description: This function returns a sentence describing how many unique traits there are for any given taxa from the taxon_name data field in AusTraits., e.g. Eucalyptus saligna
      responses:
       default:
        description: Default response
      parameters:
        - in: query
          name: taxon
          description: e.g. Eucalyptus saligna
          required: false
        - in: query
          name: APNI_ID
          description: e.g. 2912252 (For Eucalyptus saligna)
          required: false
  /trait-summary:
    get:
      summary: "For ALA: Returns the average trait value per trait for a given species"
      description: This function returns a table of summarised trait data (a simple range and mean value for numerical traits and unique categorical trait values) for a given taxa from the taxon_name data field in AusTraits
      responses:
       default:
        description: Default response
      parameters:
        - in: query
          name: taxon
          description: e.g. Eucalyptus saligna
          required: false
          schema:
            type: string
        - in: query
          name: APNI_ID
          description: e.g. e.g. 2912252 (For Eucalyptus saligna)
          required: false
          schema:
            type: string
  /download-taxon-data:
    get:
      summary: "For ALA: Downloads the csv of the raw AusTraits data used to make the trait summaries (also includes all other trait data for that taxon_name)"
      description: This function returns a table of the trait data for a given taxa from the taxon_name data field in AusTraits
      responses:
       default:
        description: Default response
      parameters:
        - in: query
          name: taxon
          description: e.g. Eucalyptus saligna
          required: false
          schema:
            type: string
        - in: query
          name: APNI_ID
          description: e.g. e.g. 2912252 (For Eucalyptus saligna)
          required: false
          schema:
            type: string
  /taxa-list:
      post:
        summary: "For Ecocommons: Returns the names unique taxa for a list of traits within the subset of austraits data that is georeferenced"
        description: This function returns an array of unique species that have data for each trait specified. Possible values for traits are found at http://traitecoevo.github.io/austraits.build/articles/austraits_database_structure.html
        responses:
         default:
          description: Default response
        requestBody:
          description: A named array of trait names
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                         traits:
                          type: array
                          example: ["seed_mass","seed_length","seed_volume"]
  /trait-list:
      post:
        summary: "For Ecocommons: Returns the names unique traits for a list of taxa"
        description: This function returns an array of unique traits that exist in AusTraits for each taxa specified within the subset of austraits data that is georeferenced.
        responses:
         default:
          description: Default response
        requestBody:
          description: A named array of taxa names
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                         taxa:
                          type: array
                          example: ["Acacia aneura","Banksia serrata","Eucalyptus saligna"]
  /taxa-autocomplete:
    get:
      summary: "For Ecocommons: Returns the species that begin with a given text string within the subset of austraits data that is georeferenced"
      description: This function returns taxon names that begin with a given text string within the subset of austraits data that is georeferenced
      responses:
       default:
        description: Default response
      parameters:
        - in: query
          name: text_string
          description: e.g. Eucal
          required: false
          schema:
            type: string
  /trait-data:
      post:
        summary: "For Ecocommons: Returns a table of the complete data available for multiple selected taxa and traits ithin the subset of austraits data that is georeferenced"
        description: This function returns a wider table of raw trait data for multiple taxa.
        responses:
         default:
          description: Default response
        parameters: []
        requestBody:
          description: A named array of species names
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                         taxa:
                          type: array
                          example: ["Acacia aneura","Acacia rostellifera","Acacia tetragonophylla"]
                         traits:
                          type: array
                          example: ["leaf_length", "leaf_width"]

  /download-trait-data:
       post:
        summary: "For Ecocommons: Returns a csv download of the complete austraits data available for multiple taxa names and traits"
        description: This function returns a download of the data for a list of taxa names and traits.
        responses:
         default:
          description: Default response
        parameters: []
        requestBody:
          description: A named array of species names and a named array of trait names
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                         taxa:
                          type: array
                          example: ["Acacia aneura","Acacia rostellifera","Acacia tetragonophylla"]
                         traits:
                          type: array
                          example: ["leaf_length", "leaf_width"]
